CREATE TABLE system_document(id INT PRIMARY KEY AUTO_INCREMENT, overview VARCHAR(30), purpose VARCHAR(255), function VARCHAR(255), period VARCHAR(30),  system_id INT);
CREATE TABLE task_document(id INT PRIMARY KEY AUTO_INCREMENT, purpose VARCHAR(255), function VARCHAR(255), item VARCHAR(255), period VARCHAR(30), task_id INT);

ALTER TABLE system_document ADD CONSTRAINT FK_SYSTEM_DOCUMENT_SYSTEM_ID FOREIGN KEY (system_id) REFERENCES system;
ALTER TABLE task_document ADD CONSTRAINT FK_TASK_DOCUMENT_TASK_ID FOREIGN KEY (task_id) REFERENCES task;